### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by OptumCS** [palmerabollo/node-isbn#2]
In very rare circumstances, on line 40 of index.js, where the volumeInfo property is being read into var book, books.items[0] is undefined.  I guess this line should be wrapped in a try/catch or other means of checking for this condition and fail more gracefully.    

Thanks for a great package!

**Comment by palmerabollo** [comment]
@OptumCS Thanks for reporting it

If you could send a fix along these lines, I'd be happy to merge it:

```
// In very rare circumstances books.items[0] is undefined (see #2)
if (!books.items || books.items.length === 0) {
    return callback(new Error('no volume info found for book with isbn: ' + isbn));
}
```

Otherwise I'll fix and test it it in 1-2 weeks.

**Comment by palmerabollo** [comment]
@OptumCS Do you have a ISBN that fails, to try to reproduce the error? It would be really helpful.
