### ISSUE TITLE
Set timeout?

### ISSUE THREAD

**Issue by infojunkie** [palmerabollo/node-isbn#3]
Is there a way to set a timeout on the request? When I run `resolve` on a long list of isbns, the call can sometimes hang for a long (minutes) amount of time. I suspect it's the http request that hangs but I haven't confirmed.

**Comment by palmerabollo** [comment]
@infojunkie node-isbn depends on the "request" module, that [supports timeout configuration](https://github.com/request/request#timeouts). node-isbn uses the default values (I don't know what they are) but you could try setting a lower value in the [requestOptions](https://github.com/palmerabollo/node-isbn/blob/master/index.js#L18-L21). Notice that there is a different `requestOptions` per service (Google Books, Open Library Books, WorldCat).

node-isbn also [limits to 500 the number of sockets to the same origin](https://github.com/palmerabollo/node-isbn/blob/master/index.js#L6), so if you are trying to resolve more than 500 books at the same time (you shouldn't), you could be reaching the limit.
