### ISSUE TITLE
Choose backend provider

### ISSUE THREAD

**Issue by infojunkie** [palmerabollo/node-isbn#6]
It would be great to optionally choose the backend provider to query, and/or to specify the order of providers to query.

**Comment by palmerabollo** [comment]
Thanks. That's a good idea.

What do you think about this external API?

```js
var isbn = require('node-isbn');
isbn.provider(['google', 'worldcat']).resolve(isbn);
```

**Comment by infojunkie** [comment]
Looks fine to me. Also, remember that the `resolve()` method now takes an optional `options` middle argument, which could be used. For example, the test at https://github.com/palmerabollo/node-isbn/blob/master/test/spec.js#L237 overrides the `timeout` setting.

**Comment by krishnagopinath** [comment]
@palmerabollo I just came across this lib; I think it would be very useful for the project I am working on! 

I was wondering if you needed assistance with adding this `provider` API. I could send a PR! 👍

**Comment by palmerabollo** [comment]
Hi @krishnagopinath. It would be great if you could contribute this "Provider API". Thank you very much.

**Comment by krishnagopinath** [comment]
@palmerabollo -- made a PR -> https://github.com/palmerabollo/node-isbn/pull/12
